version: '2'
services:
  proxy:
    image: sonatype/nexus3
    labels:
      - "traefik.backend=nexus"
      - "traefik.frontend.rule=Host:nexus.invivoo.cspinformatique.com"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_default
